#
# pacman.conf para el build de la ISO (basado en el perfil releng de archiso)
#
[options]
HoldPkg     = pacman glibc
Architecture = auto
CheckSpace
ParallelDownloads = 5
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

# Necesario para Steam, Mesa 32-bit, gamescope-session, etc.
[multilib]
Include = /etc/pacman.d/mirrorlist
