# Por defecto este modulo no activa nada (units: []); aqui activamos lo
# minimo para que la red funcione al primer arranque.
units:
  - name: "NetworkManager.service"
    action: "enable"
    mandatory: true
  - name: "systemd-timesyncd.service"
    action: "enable"
    mandatory: false
  - name: "bluetooth.service"
    action: "enable"
    mandatory: false
  - name: "sddm.service"
    action: "enable"
    mandatory: true
