# Configuracion principal de Calamares para NiranBox.
# Estructura basada en el settings.conf de referencia del propio proyecto
# Calamares (github.com/calamares/calamares), recortada a los modulos que
# necesitamos: sin displaymanager (no usamos gestor de sesiones grafico,
# arrancamos directo a Steam) y sin modulos de LUKS/ZFS (no los usamos).
modules-search: [ local ]

instances:
- id:       niranbox
  module:   shellprocess
  config:   shellprocess_niranbox.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - locale
  - keyboard
  - localecfg
  - fstab
  - users
  - networkcfg
  - hwclock
  - services-systemd
  - grubcfg
  - bootloader
  - shellprocess@niranbox
  - umount
- show:
  - finished

branding: niranbox
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: true
hide-back-and-next-during-exec: true
quit-at-end: false
